name: tempus
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.21.0
  cloud_firestore: ^3.4.5
  firebase_auth: ^3.6.4
  google_sign_in: 5.3.3
  crypto: 3.0.1
  font_awesome_flutter: 10.1.0
  provider: 6.0.3
  rxdart: 0.27.4
  json_annotation: 4.5.0
  intl: ^0.17.0
  audioplayers: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  build_runner: 2.1.11
  json_serializable: 6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
